### ISSUE TITLE
Things to finish before public opening

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/Jailbreak#14]
- [x] Prisoner Character creation/selection
- [x] HUD Redesign
- [ ] General polishing
- [ ] ???

**Comment by Sync4k** [comment]
Are you asking?  I have no idea where we are in the development process.

**Comment by Donkie** [comment]
That doesnt matter, we need to shell out a list of neccesary things that needs to be in the gamemode.

**Comment by Sync4k** [comment]
Okay, um, well it definitely needs some spunk.

**Comment by bayrock** [comment]
I assume 'general polishing' includes HUD changes?

I think it's important that we don't initially change the fundamentals of Jailbreak too much. Once we gauge the initial reaction then we can make more solid decisions.

**Comment by Donkie** [comment]
Forgot about hud changes, general polishing means things like with the wakeup, it looks cool atm but its abit buggy.

**Comment by bayrock** [comment]
Once we get a couple of these base features in I plan to devise an official teaser trailer. Should be cool. I will share it via all our social outlets including forums, group, and Facebook when the time feels right.

It will most likely include a tantalizing 'Coming Spring 2015' moment in it if all goes well.

**Comment by Sync4k** [comment]
COMING THIS SPRING, BAYROCK IN..... PRISON ESCAPE, rated R for nudity and masturbation

**Comment by jeffreythe00** [comment]
^ Don't forget about the scat. Me and bay will be doing lots of that.

**Comment by AOBatch** [comment]
I'd like to see an additional feature (Eg. Something to do with tokens) to put us just that little bit more above the rest upon release

**Comment by AOBatch** [comment]
:o: Skins for weapons
:o: Achievements
:o: Perks of some sort

Just a few smaller things that I thought might be good on initial release, but I'm not sure what you're working on

**Comment by Donkie** [comment]
@RicksBeehive the idea is to cut down on stupid features so we can release earlier

**Comment by bayrock** [comment]
The initial networking of VIP ranks/tokens and all could be good. Weapon skins can be available for token purchase when it becomes viable, and whatnot.

Also, you mentioned the ranking system for guards. Maybe start that before release too.

**Comment by AOBatch** [comment]
@Donkie I thought the idea was to get at least one actually interesting feature so that we can release something chill
