### ISSUE TITLE
Suggestion : Purchasable rank

### ISSUE THREAD

**Issue by DuckZevnov** [GMDevinity/Jailbreak#16]
I'm not sure if there will still be the same ranks you can buy in the jailbreak server; Like "Bronze/Silver/Gold/Platinum."

If not there should be a "VIP" and "Elite VIP" Rank that can be purchasable.
Not only will it allow Bayrock to gain some money the VIP and Elite VIP rank can have some advantages that wont necessarily effect gameplay but can have "Vote-kick" or "Vote-ban" just in case that there will be no staff online.

**Comment by AOBatch** [comment]
We've spoken about this briefly and I think Bayrock is having his mind set that your rank will be Across the Board. In that if you Donate on one server then you also get that rank on the other server. But we're not sure what bonuses it'll have on the actual server.
