### ISSUE TITLE
Teamchat

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/Jailbreak#21]
Whenever a guard kills someone, he will automatically announce in teamchat "I killed X using my Y!"
If a guard sees a prisoner do something, like fall and die, he will announce "I saw X kill himself!"
"I saw X gun down Y"
...?

**Comment by Donkie** [comment]
This will be nice cause its easy to keep track of whats happening and its easy to find freekillers

**Comment by Donkie** [comment]
This is something you can do @bayrock , atleast the first one. http://wiki.garrysmod.com/page/GM/PlayerDeath

**Comment by bayrock** [comment]
![example](http://f.bay.rocks/GiGDL)

Still need to look into the other types of announcements.

**Comment by Donkie** [comment]
:+1:

**Comment by AOBatch** [comment]
We need a way to distinguish between genuine kills and people literally saying "I killed Bayrock with my Deagle".

**Comment by Donkie** [comment]
Not really,  the point of this is to erase radiocomms. Only guards will say it

**Comment by bayrock** [comment]
The inflicting guard also emit a sound when the kill is genuine.
